//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Principal.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterado com sucesso.
        /// </summary>
        public static string AlteradoSucesso {
            get {
                return ResourceManager.GetString("AlteradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro deve conter entre 4 a 20 caracteres.
        /// </summary>
        public static string BairroDeveConter {
            get {
                return ResourceManager.GetString("BairroDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro deve ser Preenchido.
        /// </summary>
        public static string BairroPreenchido {
            get {
                return ResourceManager.GetString("BairroPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Básicos.
        /// </summary>
        public static string Basicos {
            get {
                return ResourceManager.GetString("Basicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrado com sucesso.
        /// </summary>
        public static string CadastradoSucesso {
            get {
                return ResourceManager.GetString("CadastradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Trabalho.
        /// </summary>
        public static string CarteiraDeTrabalho {
            get {
                return ResourceManager.GetString("CarteiraDeTrabalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Trabalho deve conter somentes dígitos.
        /// </summary>
        public static string CarteiraTrabalhoDigitos {
            get {
                return ResourceManager.GetString("CarteiraTrabalhoDigitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Trabalho deve ser Preenchido.
        /// </summary>
        public static string CarteiraTrabalhoPreenchido {
            get {
                return ResourceManager.GetString("CarteiraTrabalhoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP deve conter 9 caracteres.
        /// </summary>
        public static string CEPDeveConter {
            get {
                return ResourceManager.GetString("CEPDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP deve ser Preenchido.
        /// </summary>
        public static string CEPPreenchido {
            get {
                return ResourceManager.GetString("CEPPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Cidade {
            get {
                return ResourceManager.GetString("Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade deve conter entre 3 a 30 caracteres.
        /// </summary>
        public static string CidadeDeveConterEntre {
            get {
                return ResourceManager.GetString("CidadeDeveConterEntre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade deve ser Preenchido.
        /// </summary>
        public static string CidadePreenchido {
            get {
                return ResourceManager.GetString("CidadePreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidades.
        /// </summary>
        public static string Cidades {
            get {
                return ResourceManager.GetString("Cidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string Classificacao {
            get {
                return ResourceManager.GetString("Classificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string Complemento {
            get {
                return ResourceManager.GetString("Complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continente.
        /// </summary>
        public static string Continente {
            get {
                return ResourceManager.GetString("Continente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF deve ser Preenchido.
        /// </summary>
        public static string CpfPreenchido {
            get {
                return ResourceManager.GetString("CpfPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string DataNascimento {
            get {
                return ResourceManager.GetString("DataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento Inválida.
        /// </summary>
        public static string DataNascimentoInvalido {
            get {
                return ResourceManager.GetString("DataNascimentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento deve ser Preenchido.
        /// </summary>
        public static string DataNascimentoPreenchido {
            get {
                return ResourceManager.GetString("DataNascimentoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data não é válida.
        /// </summary>
        public static string DataValida {
            get {
                return ResourceManager.GetString("DataValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativado com sucesso.
        /// </summary>
        public static string DesativadoSucesso {
            get {
                return ResourceManager.GetString("DesativadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços.
        /// </summary>
        public static string Enderecos {
            get {
                return ResourceManager.GetString("Enderecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado deve conter entre 2 a 30 caracteres.
        /// </summary>
        public static string EstadoDeveConter {
            get {
                return ResourceManager.GetString("EstadoDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado deve ser Preenchido.
        /// </summary>
        public static string EstadoPreenchido {
            get {
                return ResourceManager.GetString("EstadoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estados.
        /// </summary>
        public static string Estados {
            get {
                return ResourceManager.GetString("Estados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero.
        /// </summary>
        public static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero deve ser preenchido.
        /// </summary>
        public static string GeneroPreenchido {
            get {
                return ResourceManager.GetString("GeneroPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guia.
        /// </summary>
        public static string Guia {
            get {
                return ResourceManager.GetString("Guia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Habilitação deve conter entre 1 a 5 caracteres.
        /// </summary>
        public static string HabilitacaoDeveConter {
            get {
                return ResourceManager.GetString("HabilitacaoDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Habilitação deve ser Preenchido.
        /// </summary>
        public static string HabilitacaoPreenchida {
            get {
                return ResourceManager.GetString("HabilitacaoPreenchida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico de Viagem.
        /// </summary>
        public static string HistoricoViagem {
            get {
                return ResourceManager.GetString("HistoricoViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idade.
        /// </summary>
        public static string Idade {
            get {
                return ResourceManager.GetString("Idade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma deve conter entre 4 a 20 caracteres.
        /// </summary>
        public static string IdiomaDeveConter {
            get {
                return ResourceManager.GetString("IdiomaDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma deve ser Preenchido.
        /// </summary>
        public static string IdiomaPreenchido {
            get {
                return ResourceManager.GetString("IdiomaPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        public static string Idiomas {
            get {
                return ResourceManager.GetString("Idiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Data.
        /// </summary>
        public static string InformeData {
            get {
                return ResourceManager.GetString("InformeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Data de Saída.
        /// </summary>
        public static string InformeDataSaida {
            get {
                return ResourceManager.GetString("InformeDataSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a data da Volta.
        /// </summary>
        public static string InformeDataVolta {
            get {
                return ResourceManager.GetString("InformeDataVolta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro deve conter entre 6 a 30 caracteres.
        /// </summary>
        public static string LogradouroDeveConter {
            get {
                return ResourceManager.GetString("LogradouroDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro deve ser Preenchido.
        /// </summary>
        public static string LogradouroPreenchido {
            get {
                return ResourceManager.GetString("LogradouroPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome deve conter entre 3 a 30 caracteres.
        /// </summary>
        public static string NomeDeveConter {
            get {
                return ResourceManager.GetString("NomeDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome deve ser Preenchido.
        /// </summary>
        public static string NomePreenchido {
            get {
                return ResourceManager.GetString("NomePreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número deve conter apenas dígitos.
        /// </summary>
        public static string NumeroDigitos {
            get {
                return ResourceManager.GetString("NumeroDigitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número deve ser Preenchido.
        /// </summary>
        public static string NumeroPreenchido {
            get {
                return ResourceManager.GetString("NumeroPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacote.
        /// </summary>
        public static string Pacote {
            get {
                return ResourceManager.GetString("Pacote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacote deve conter entre 3 a 30 caracteres.
        /// </summary>
        public static string PacoteDeveConter {
            get {
                return ResourceManager.GetString("PacoteDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacote Ponto Turistico.
        /// </summary>
        public static string PacotePontoTuristico {
            get {
                return ResourceManager.GetString("PacotePontoTuristico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacote deve ser Preenchido.
        /// </summary>
        public static string PacotePreenchido {
            get {
                return ResourceManager.GetString("PacotePreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacotes.
        /// </summary>
        public static string Pacotes {
            get {
                return ResourceManager.GetString("Pacotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual máximo de desconto deve ser Preenchido.
        /// </summary>
        public static string PercentualDesconto {
            get {
                return ResourceManager.GetString("PercentualDesconto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual máximo de desconto deve conter números inteiros ou decimais.
        /// </summary>
        public static string PercentualDescontoDeveConter {
            get {
                return ResourceManager.GetString("PercentualDescontoDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual máximo de desconto deve ser entre 1 % a 100%.
        /// </summary>
        public static string PercentualDescontoDeveSer {
            get {
                return ResourceManager.GetString("PercentualDescontoDeveSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontos Turísticos.
        /// </summary>
        public static string PontosTuristicos {
            get {
                return ResourceManager.GetString("PontosTuristicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto Turístico.
        /// </summary>
        public static string PontoTuristico {
            get {
                return ResourceManager.GetString("PontoTuristico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto Turístico deve conter entre 3 a 30 caracteres.
        /// </summary>
        public static string PontoTuristicoDeveConter {
            get {
                return ResourceManager.GetString("PontoTuristicoDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto Turistico deve ser Preenchido.
        /// </summary>
        public static string PontoTuristicoPreenchido {
            get {
                return ResourceManager.GetString("PontoTuristicoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referência.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG deve conter apenas dígitos.
        /// </summary>
        public static string RgDigitos {
            get {
                return ResourceManager.GetString("RgDigitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG deve conter no máximo 12 dígitos.
        /// </summary>
        public static string RgMaximo {
            get {
                return ResourceManager.GetString("RgMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG deve conter no mínimo 7 dígitos.
        /// </summary>
        public static string RgMinimo {
            get {
                return ResourceManager.GetString("RgMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG deve ser preenchido.
        /// </summary>
        public static string RgPreenchido {
            get {
                return ResourceManager.GetString("RgPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário deve ser entre R$ 954,00 a R$ 10.000,00.
        /// </summary>
        public static string SalalarioDeveSer {
            get {
                return ResourceManager.GetString("SalalarioDeveSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário.
        /// </summary>
        public static string Salario {
            get {
                return ResourceManager.GetString("Salario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário deve conter apenas números inteiros e decimais.
        /// </summary>
        public static string SalarioDigitosDecimais {
            get {
                return ResourceManager.GetString("SalarioDigitosDecimais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário deve conter no mínimo 3 dígitos.
        /// </summary>
        public static string SalarioMinimo {
            get {
                return ResourceManager.GetString("SalarioMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário deve ser Preenchido.
        /// </summary>
        public static string SalarioPreenchido {
            get {
                return ResourceManager.GetString("SalarioPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um Estado.
        /// </summary>
        public static string SelecioneEstado {
            get {
                return ResourceManager.GetString("SelecioneEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um Guia.
        /// </summary>
        public static string SelecioneGuia {
            get {
                return ResourceManager.GetString("SelecioneGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um Pacote.
        /// </summary>
        public static string SelecionePacote {
            get {
                return ResourceManager.GetString("SelecionePacote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleione um Ponto Turístico.
        /// </summary>
        public static string SelecionePontoTuristico {
            get {
                return ResourceManager.GetString("SelecionePontoTuristico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string Sobrenome {
            get {
                return ResourceManager.GetString("Sobrenome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome deve conter entre 3 a 30 caracteres.
        /// </summary>
        public static string SobrenomeDeveConter {
            get {
                return ResourceManager.GetString("SobrenomeDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome deve ser Preenchido.
        /// </summary>
        public static string SobrenomePrenchido {
            get {
                return ResourceManager.GetString("SobrenomePrenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve ser entre R$ 500,00 a R$ 12.000,00.
        /// </summary>
        public static string ValorDeveSer {
            get {
                return ResourceManager.GetString("ValorDeveSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve conter apenas números inteiros e decimais.
        /// </summary>
        public static string ValorInteros {
            get {
                return ResourceManager.GetString("ValorInteros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve ser Preenchido.
        /// </summary>
        public static string ValorPreenchido {
            get {
                return ResourceManager.GetString("ValorPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Viagem {
            get {
                return ResourceManager.GetString("Viagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagens.
        /// </summary>
        public static string Viagens {
            get {
                return ResourceManager.GetString("Viagens", resourceCulture);
            }
        }
    }
}
