//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Principal.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação.
        /// </summary>
        public static string Acao {
            get {
                return ResourceManager.GetString("Acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to África.
        /// </summary>
        public static string Africa {
            get {
                return ResourceManager.GetString("Africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterado com sucesso.
        /// </summary>
        public static string AlteradoSucesso {
            get {
                return ResourceManager.GetString("AlteradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to América.
        /// </summary>
        public static string America {
            get {
                return ResourceManager.GetString("America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string Anterior {
            get {
                return ResourceManager.GetString("Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Apresentar {
            get {
                return ResourceManager.GetString("Apresentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovação.
        /// </summary>
        public static string Aprovacao {
            get {
                return ResourceManager.GetString("Aprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ásia.
        /// </summary>
        public static string Asia {
            get {
                return ResourceManager.GetString("Asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avançado.
        /// </summary>
        public static string Avancado {
            get {
                return ResourceManager.GetString("Avancado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro deve conter entre 4 a 20 caracteres.
        /// </summary>
        public static string BairroDeveConter {
            get {
                return ResourceManager.GetString("BairroDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro deve ser Preenchido.
        /// </summary>
        public static string BairroPreenchido {
            get {
                return ResourceManager.GetString("BairroPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Básicos.
        /// </summary>
        public static string Basicos {
            get {
                return ResourceManager.GetString("Basicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrado com sucesso.
        /// </summary>
        public static string CadastradoSucesso {
            get {
                return ResourceManager.GetString("CadastradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        public static string Cadastrar {
            get {
                return ResourceManager.GetString("Cadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Histórico de Viagem.
        /// </summary>
        public static string CadastrarHV {
            get {
                return ResourceManager.GetString("CadastrarHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Pacote.
        /// </summary>
        public static string CadastrarPacote {
            get {
                return ResourceManager.GetString("CadastrarPacote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Pacote Ponto Turístico.
        /// </summary>
        public static string CadastrarPPT {
            get {
                return ResourceManager.GetString("CadastrarPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Cidade.
        /// </summary>
        public static string CadastroCidade {
            get {
                return ResourceManager.GetString("CadastroCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Endereço.
        /// </summary>
        public static string CadastroEndereco {
            get {
                return ResourceManager.GetString("CadastroEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Estado.
        /// </summary>
        public static string CadastroEstado {
            get {
                return ResourceManager.GetString("CadastroEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Idioma.
        /// </summary>
        public static string CadastroIdioma {
            get {
                return ResourceManager.GetString("CadastroIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastros.
        /// </summary>
        public static string Cadastros {
            get {
                return ResourceManager.GetString("Cadastros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Viagem.
        /// </summary>
        public static string CadastroViagem {
            get {
                return ResourceManager.GetString("CadastroViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando....
        /// </summary>
        public static string Carregando {
            get {
                return ResourceManager.GetString("Carregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Trabalho.
        /// </summary>
        public static string CarteiraDeTrabalho {
            get {
                return ResourceManager.GetString("CarteiraDeTrabalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Trabalho deve conter somentes dígitos.
        /// </summary>
        public static string CarteiraTrabalhoDigitos {
            get {
                return ResourceManager.GetString("CarteiraTrabalhoDigitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Trabalho deve ser Preenchido.
        /// </summary>
        public static string CarteiraTrabalhoPreenchido {
            get {
                return ResourceManager.GetString("CarteiraTrabalhoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP deve conter 8 caracteres.
        /// </summary>
        public static string CEPDeveConter {
            get {
                return ResourceManager.GetString("CEPDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP deve ser Preenchido.
        /// </summary>
        public static string CEPPreenchido {
            get {
                return ResourceManager.GetString("CEPPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Global.
        /// </summary>
        public static string ChatGlobal {
            get {
                return ResourceManager.GetString("ChatGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Cidade {
            get {
                return ResourceManager.GetString("Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade deve conter entre 3 a 30 caracteres.
        /// </summary>
        public static string CidadeDeveConterEntre {
            get {
                return ResourceManager.GetString("CidadeDeveConterEntre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade deve ser Preenchido.
        /// </summary>
        public static string CidadePreenchido {
            get {
                return ResourceManager.GetString("CidadePreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidades.
        /// </summary>
        public static string Cidades {
            get {
                return ResourceManager.GetString("Cidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string Classificacao {
            get {
                return ResourceManager.GetString("Classificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string Complemento {
            get {
                return ResourceManager.GetString("Complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Pacotes.
        /// </summary>
        public static string ConfirmarPacotes {
            get {
                return ResourceManager.GetString("ConfirmarPacotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continente.
        /// </summary>
        public static string Continente {
            get {
                return ResourceManager.GetString("Continente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um CPF válido.
        /// </summary>
        public static string CpfInvalido {
            get {
                return ResourceManager.GetString("CpfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF deve ser Preenchido.
        /// </summary>
        public static string CpfPreenchido {
            get {
                return ResourceManager.GetString("CpfPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação do Usuário (Provisório).
        /// </summary>
        public static string CriacaoUsuario {
            get {
                return ResourceManager.GetString("CriacaoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Pacote.
        /// </summary>
        public static string CriarPacote {
            get {
                return ResourceManager.GetString("CriarPacote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e Horário de Ida.
        /// </summary>
        public static string DataHorarioIda {
            get {
                return ResourceManager.GetString("DataHorarioIda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e Horário de Volta.
        /// </summary>
        public static string DataHorarioVolta {
            get {
                return ResourceManager.GetString("DataHorarioVolta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string DataNascimento {
            get {
                return ResourceManager.GetString("DataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento Inválida.
        /// </summary>
        public static string DataNascimentoInvalido {
            get {
                return ResourceManager.GetString("DataNascimentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento deve ser Preenchido.
        /// </summary>
        public static string DataNascimentoPreenchido {
            get {
                return ResourceManager.GetString("DataNascimentoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data não é válida.
        /// </summary>
        public static string DataValida {
            get {
                return ResourceManager.GetString("DataValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativado!.
        /// </summary>
        public static string Desativado {
            get {
                return ResourceManager.GetString("Desativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativado com sucesso.
        /// </summary>
        public static string DesativadoSucesso {
            get {
                return ResourceManager.GetString("DesativadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar.
        /// </summary>
        public static string Desativar {
            get {
                return ResourceManager.GetString("Desativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconto.
        /// </summary>
        public static string Desconto {
            get {
                return ResourceManager.GetString("Desconto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cidade.
        /// </summary>
        public static string EditarCidade {
            get {
                return ResourceManager.GetString("EditarCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Endereços.
        /// </summary>
        public static string EditarEnderecos {
            get {
                return ResourceManager.GetString("EditarEnderecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Estado.
        /// </summary>
        public static string EditarEstado {
            get {
                return ResourceManager.GetString("EditarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Histórico de Viagem.
        /// </summary>
        public static string EditarHV {
            get {
                return ResourceManager.GetString("EditarHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Idioma.
        /// </summary>
        public static string EditarIdioma {
            get {
                return ResourceManager.GetString("EditarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Pacote.
        /// </summary>
        public static string EditarPacote {
            get {
                return ResourceManager.GetString("EditarPacote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Pacote Ponto Turístico.
        /// </summary>
        public static string EditarPPT {
            get {
                return ResourceManager.GetString("EditarPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Viagem.
        /// </summary>
        public static string EditarViagem {
            get {
                return ResourceManager.GetString("EditarViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço Cadastrado com Sucesso.
        /// </summary>
        public static string EnderecoCadastradoSucesso {
            get {
                return ResourceManager.GetString("EnderecoCadastradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço desativado com Sucesso.
        /// </summary>
        public static string EnderecoDesativadoSucesso {
            get {
                return ResourceManager.GetString("EnderecoDesativadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço alterado com Sucesso.
        /// </summary>
        public static string EnderecoEditadoSucesso {
            get {
                return ResourceManager.GetString("EnderecoEditadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços.
        /// </summary>
        public static string Enderecos {
            get {
                return ResourceManager.GetString("Enderecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado deve conter entre 2 a 30 caracteres.
        /// </summary>
        public static string EstadoDeveConter {
            get {
                return ResourceManager.GetString("EstadoDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado deve ser Preenchido.
        /// </summary>
        public static string EstadoPreenchido {
            get {
                return ResourceManager.GetString("EstadoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estados.
        /// </summary>
        public static string Estados {
            get {
                return ResourceManager.GetString("Estados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europa.
        /// </summary>
        public static string Europa {
            get {
                return ResourceManager.GetString("Europa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrados.
        /// </summary>
        public static string filtrados {
            get {
                return ResourceManager.GetString("filtrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filtrados de.
        /// </summary>
        public static string filtradosde {
            get {
                return ResourceManager.GetString("filtradosde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero.
        /// </summary>
        public static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero deve ser preenchido.
        /// </summary>
        public static string GeneroPreenchido {
            get {
                return ResourceManager.GetString("GeneroPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guia.
        /// </summary>
        public static string Guia {
            get {
                return ResourceManager.GetString("Guia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guias.
        /// </summary>
        public static string Guias {
            get {
                return ResourceManager.GetString("Guias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Habilitação deve conter entre 1 a 5 caracteres.
        /// </summary>
        public static string HabilitacaoDeveConter {
            get {
                return ResourceManager.GetString("HabilitacaoDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Habilitação deve ser Preenchido.
        /// </summary>
        public static string HabilitacaoPreenchida {
            get {
                return ResourceManager.GetString("HabilitacaoPreenchida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico de Viagem.
        /// </summary>
        public static string HistoricoViagem {
            get {
                return ResourceManager.GetString("HistoricoViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idade.
        /// </summary>
        public static string Idade {
            get {
                return ResourceManager.GetString("Idade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma deve conter entre 4 a 20 caracteres.
        /// </summary>
        public static string IdiomaDeveConter {
            get {
                return ResourceManager.GetString("IdiomaDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma deve ser Preenchido.
        /// </summary>
        public static string IdiomaPreenchido {
            get {
                return ResourceManager.GetString("IdiomaPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        public static string Idiomas {
            get {
                return ResourceManager.GetString("Idiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Data.
        /// </summary>
        public static string InformeData {
            get {
                return ResourceManager.GetString("InformeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Data de Saída.
        /// </summary>
        public static string InformeDataSaida {
            get {
                return ResourceManager.GetString("InformeDataSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a data da Volta.
        /// </summary>
        public static string InformeDataVolta {
            get {
                return ResourceManager.GetString("InformeDataVolta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        public static string Logradouro {
            get {
                return ResourceManager.GetString("Logradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro deve conter entre 6 a 30 caracteres.
        /// </summary>
        public static string LogradouroDeveConter {
            get {
                return ResourceManager.GetString("LogradouroDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro deve ser Preenchido.
        /// </summary>
        public static string LogradouroPreenchido {
            get {
                return ResourceManager.GetString("LogradouroPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meu Perfil.
        /// </summary>
        public static string MeuPerfil {
            get {
                return ResourceManager.GetString("MeuPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando Página.
        /// </summary>
        public static string MostrandoPagina {
            get {
                return ResourceManager.GetString("MostrandoPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum Registro Disponível.
        /// </summary>
        public static string NenhumRegistroDisponivel {
            get {
                return ResourceManager.GetString("NenhumRegistroDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum Registro foi encontrado.
        /// </summary>
        public static string NenhumRegistroEncontrado {
            get {
                return ResourceManager.GetString("NenhumRegistroEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome deve conter entre 3 a 30 caracteres.
        /// </summary>
        public static string NomeDeveConter {
            get {
                return ResourceManager.GetString("NomeDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome deve ser Preenchido.
        /// </summary>
        public static string NomePreenchido {
            get {
                return ResourceManager.GetString("NomePreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número deve conter apenas dígitos.
        /// </summary>
        public static string NumeroDigitos {
            get {
                return ResourceManager.GetString("NumeroDigitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número deve ser Preenchido.
        /// </summary>
        public static string NumeroPreenchido {
            get {
                return ResourceManager.GetString("NumeroPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceânia.
        /// </summary>
        public static string Oceania {
            get {
                return ResourceManager.GetString("Oceania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Ordenar Colunas de forma ascendente.
        /// </summary>
        public static string OrdenarAscendentes {
            get {
                return ResourceManager.GetString("OrdenarAscendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Ordenar Colunas de forma descendente.
        /// </summary>
        public static string OrdenarDescendentes {
            get {
                return ResourceManager.GetString("OrdenarDescendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacote.
        /// </summary>
        public static string Pacote {
            get {
                return ResourceManager.GetString("Pacote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacote deve conter entre 3 a 30 caracteres.
        /// </summary>
        public static string PacoteDeveConter {
            get {
                return ResourceManager.GetString("PacoteDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Pacote.
        /// </summary>
        public static string PacoteNome {
            get {
                return ResourceManager.GetString("PacoteNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacote Ponto Turistico.
        /// </summary>
        public static string PacotePontoTuristico {
            get {
                return ResourceManager.GetString("PacotePontoTuristico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacote deve ser Preenchido.
        /// </summary>
        public static string PacotePreenchido {
            get {
                return ResourceManager.GetString("PacotePreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacotes.
        /// </summary>
        public static string Pacotes {
            get {
                return ResourceManager.GetString("Pacotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual de Desconto.
        /// </summary>
        public static string PercentualDesconto {
            get {
                return ResourceManager.GetString("PercentualDesconto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual máximo de desconto deve conter números inteiros ou decimais.
        /// </summary>
        public static string PercentualDescontoDeveConter {
            get {
                return ResourceManager.GetString("PercentualDescontoDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual máximo de desconto deve ser entre 1 % a 100%.
        /// </summary>
        public static string PercentualDescontoDeveSer {
            get {
                return ResourceManager.GetString("PercentualDescontoDeveSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual máximo de desconto deve ser Preenchido.
        /// </summary>
        public static string PercentualDescontoPreenchido {
            get {
                return ResourceManager.GetString("PercentualDescontoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontos Turísticos.
        /// </summary>
        public static string PontosTuristicos {
            get {
                return ResourceManager.GetString("PontosTuristicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto Turístico.
        /// </summary>
        public static string PontoTuristico {
            get {
                return ResourceManager.GetString("PontoTuristico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto Turístico deve conter entre 3 a 30 caracteres.
        /// </summary>
        public static string PontoTuristicoDeveConter {
            get {
                return ResourceManager.GetString("PontoTuristicoDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto Turistico deve ser Preenchido.
        /// </summary>
        public static string PontoTuristicoPreenchido {
            get {
                return ResourceManager.GetString("PontoTuristicoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro.
        /// </summary>
        public static string Primeiro {
            get {
                return ResourceManager.GetString("Primeiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando....
        /// </summary>
        public static string Processando {
            get {
                return ResourceManager.GetString("Processando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo.
        /// </summary>
        public static string Proximo {
            get {
                return ResourceManager.GetString("Proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referência.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG deve conter apenas dígitos.
        /// </summary>
        public static string RgDigitos {
            get {
                return ResourceManager.GetString("RgDigitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG deve conter no máximo 12 dígitos.
        /// </summary>
        public static string RgMaximo {
            get {
                return ResourceManager.GetString("RgMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG deve conter no mínimo 7 dígitos.
        /// </summary>
        public static string RgMinimo {
            get {
                return ResourceManager.GetString("RgMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG deve ser preenchido.
        /// </summary>
        public static string RgPreenchido {
            get {
                return ResourceManager.GetString("RgPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário deve ser entre R$ 954,00 a R$ 10.000,00.
        /// </summary>
        public static string SalalarioDeveSer {
            get {
                return ResourceManager.GetString("SalalarioDeveSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário.
        /// </summary>
        public static string Salario {
            get {
                return ResourceManager.GetString("Salario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário deve conter apenas números inteiros e decimais.
        /// </summary>
        public static string SalarioDigitosDecimais {
            get {
                return ResourceManager.GetString("SalarioDigitosDecimais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário deve conter no mínimo 3 dígitos.
        /// </summary>
        public static string SalarioMinimo {
            get {
                return ResourceManager.GetString("SalarioMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário deve ser Preenchido.
        /// </summary>
        public static string SalarioPreenchido {
            get {
                return ResourceManager.GetString("SalarioPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um destino.
        /// </summary>
        public static string SelecioneDestino {
            get {
                return ResourceManager.GetString("SelecioneDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um Estado.
        /// </summary>
        public static string SelecioneEstado {
            get {
                return ResourceManager.GetString("SelecioneEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um Guia.
        /// </summary>
        public static string SelecioneGuia {
            get {
                return ResourceManager.GetString("SelecioneGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um Pacote.
        /// </summary>
        public static string SelecionePacote {
            get {
                return ResourceManager.GetString("SelecionePacote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleione um Ponto Turístico.
        /// </summary>
        public static string SelecionePontoTuristico {
            get {
                return ResourceManager.GetString("SelecionePontoTuristico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo deve ser preenchido.
        /// </summary>
        public static string Sexo {
            get {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string Sobrenome {
            get {
                return ResourceManager.GetString("Sobrenome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome deve conter entre 3 a 30 caracteres.
        /// </summary>
        public static string SobrenomeDeveConter {
            get {
                return ResourceManager.GetString("SobrenomeDeveConter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome deve ser Preenchido.
        /// </summary>
        public static string SobrenomePrenchido {
            get {
                return ResourceManager.GetString("SobrenomePrenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua mensagem aqui.
        /// </summary>
        public static string SuaMensagemAqui {
            get {
                return ResourceManager.GetString("SuaMensagemAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso!.
        /// </summary>
        public static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Cidades.
        /// </summary>
        public static string TabelaCidades {
            get {
                return ResourceManager.GetString("TabelaCidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Endereços.
        /// </summary>
        public static string TabelaEnderecos {
            get {
                return ResourceManager.GetString("TabelaEnderecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Estados.
        /// </summary>
        public static string TabelaEstados {
            get {
                return ResourceManager.GetString("TabelaEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Guias.
        /// </summary>
        public static string TabelaGuias {
            get {
                return ResourceManager.GetString("TabelaGuias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Histórico de Viagem.
        /// </summary>
        public static string TabelaHV {
            get {
                return ResourceManager.GetString("TabelaHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Idiomas.
        /// </summary>
        public static string TabelaIdiomas {
            get {
                return ResourceManager.GetString("TabelaIdiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Pacotes.
        /// </summary>
        public static string TabelaPacotes {
            get {
                return ResourceManager.GetString("TabelaPacotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Pacote Ponto Turístico.
        /// </summary>
        public static string TabelaPPT {
            get {
                return ResourceManager.GetString("TabelaPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Ponto Turístico.
        /// </summary>
        public static string TabelaPT {
            get {
                return ResourceManager.GetString("TabelaPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Viagens.
        /// </summary>
        public static string TabelaViagens {
            get {
                return ResourceManager.GetString("TabelaViagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Viagem Turista.
        /// </summary>
        public static string TabelaVT {
            get {
                return ResourceManager.GetString("TabelaVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Bloqueio.
        /// </summary>
        public static string TelaBloqueio {
            get {
                return ResourceManager.GetString("TelaBloqueio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Cidades.
        /// </summary>
        public static string TelaGerenciamentoCidade {
            get {
                return ResourceManager.GetString("TelaGerenciamentoCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Endereços.
        /// </summary>
        public static string TelaGerenciamentoEndereco {
            get {
                return ResourceManager.GetString("TelaGerenciamentoEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Estados.
        /// </summary>
        public static string TelaGerenciamentoEstado {
            get {
                return ResourceManager.GetString("TelaGerenciamentoEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Guias.
        /// </summary>
        public static string TelaGerenciamentoGuias {
            get {
                return ResourceManager.GetString("TelaGerenciamentoGuias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Histórico de Viagem.
        /// </summary>
        public static string TelaGerenciamentoHV {
            get {
                return ResourceManager.GetString("TelaGerenciamentoHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Idiomas.
        /// </summary>
        public static string TelaGerenciamentoIdiomas {
            get {
                return ResourceManager.GetString("TelaGerenciamentoIdiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Pacotes.
        /// </summary>
        public static string TelaGerenciamentoPacotes {
            get {
                return ResourceManager.GetString("TelaGerenciamentoPacotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Pacote Ponto Turistico.
        /// </summary>
        public static string TelaGerenciamentoPPT {
            get {
                return ResourceManager.GetString("TelaGerenciamentoPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Ponto Turístico.
        /// </summary>
        public static string TelaGerenciamentoTA {
            get {
                return ResourceManager.GetString("TelaGerenciamentoTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Viagens.
        /// </summary>
        public static string TelaGerenciamentoViagens {
            get {
                return ResourceManager.GetString("TelaGerenciamentoViagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Gerenciamento de Viagem Turista.
        /// </summary>
        public static string TelaGerenciamentoVT {
            get {
                return ResourceManager.GetString("TelaGerenciamentoVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teste.
        /// </summary>
        public static string Teste {
            get {
                return ResourceManager.GetString("Teste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turistas.
        /// </summary>
        public static string Turistas {
            get {
                return ResourceManager.GetString("Turistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último.
        /// </summary>
        public static string Ultimo {
            get {
                return ResourceManager.GetString("Ultimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve ser entre R$ 500,00 a R$ 12.000,00.
        /// </summary>
        public static string ValorDeveSer {
            get {
                return ResourceManager.GetString("ValorDeveSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve conter apenas números inteiros e decimais.
        /// </summary>
        public static string ValorInteros {
            get {
                return ResourceManager.GetString("ValorInteros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve ser Preenchido.
        /// </summary>
        public static string ValorPreenchido {
            get {
                return ResourceManager.GetString("ValorPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total: R$.
        /// </summary>
        public static string ValorTotal {
            get {
                return ResourceManager.GetString("ValorTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Viagem {
            get {
                return ResourceManager.GetString("Viagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem Turista.
        /// </summary>
        public static string ViagemTurista {
            get {
                return ResourceManager.GetString("ViagemTurista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagens.
        /// </summary>
        public static string Viagens {
            get {
                return ResourceManager.GetString("Viagens", resourceCulture);
            }
        }
    }
}
